import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Activity,
  BookOpen,
  BrainCircuit,
  Check,
  Database,
  Download,
  Edit2,
  FileText,
  Folder,
  Hexagon,
  Layers,
  Menu,
  PanelLeftClose,
  Paperclip,
  RefreshCw,
  Redo2,
  Save,
  Send,
  Settings,
  ShieldCheck,
  Tag,
  Trash2,
  Undo2,
  Upload,
  X,
  Zap
} from 'lucide-react';
import { cn } from '@/lib/utils';

export interface KnowledgeItem {
  id: string;
  name: string;
  content: string;
  type: 'text' | 'image' | 'code';
}

export interface ActiveUpload {
  name: string;
  mimeType: string;
  data: string;
}

export interface EngineMetrics {
  latencyMs: number;
  tokensIn: number;
  tokensOut: number;
  costUsd: number;
  protocol: string;
}

export interface EngineResponse {
  id: string;
  timestamp: number;
  query: string;
  content: string;
  metrics: EngineMetrics;
  status: 'complete' | 'error' | 'processing';
  metaReflection?: string;
}

export interface SavedSession {
  id: string;
  title: string;
  tags: string[];
  folder: string;
  history: EngineResponse[];
  timestamp: number;
}

export interface GenerateEngineResponseResult {
  content: string;
  metrics: EngineMetrics;
  metaReflection: string;
}

export interface GenerateAutoTagsResult {
  folder: string;
  tags: string[];
}

export type SidebarTab = 'engine' | 'library';

export interface SessionEditForm {
  title: string;
  tags: string;
  folder: string;
}

const INITIAL_METRICS: EngineMetrics = {
  latencyMs: 0,
  tokensIn: 0,
  tokensOut: 0,
  costUsd: 0,
  protocol: 'Ultimate Nihiltheistic Inquiry Protocol'
};

const APP_CONFIG = {
  MAX_HISTORY_STACK: 50,
  MAX_FILE_SIZE_MB: 5,
  SUPPORTED_KNOWLEDGE_MIMES: [
    'text/plain',
    'application/json',
    'application/javascript',
    'text/markdown',
    'text/html',
    'application/xml'
  ],
  EXPORT_FILENAME_PREFIX: 'UNC_Session',
  ERROR_PROTOCOL_FAILURE:
    "### PROTOCOL FAILURE\nThe Ultimate Nihiltheistic Inquiry Protocol encountered a recursive collapse. The query could not be mapped to the void.",
  KNOWLEDGE_ASSIMILATION_ALERT: 'Only text-based files can be assimilated into the Knowledge Base currently.'
};

async function generateEngineResponse(
  query: string,
  customInstruction: string,
  knowledgeBase: KnowledgeItem[],
  activeUploads: ActiveUpload[]
): Promise<GenerateEngineResponseResult> {
  await new Promise((resolve) => setTimeout(resolve, 1500));

  const metrics: EngineMetrics = {
    ...INITIAL_METRICS,
    latencyMs: Math.floor(Math.random() * 1000) + 500,
    tokensIn:
      query.length +
      customInstruction.length +
      knowledgeBase.reduce((sum, item) => sum + item.content.length, 0),
    tokensOut: 500,
    costUsd: 0.0015
  };

  const content = `// Response generated by the UNC Engine.\n// Query: ${query}\n// Context Saturation: ${knowledgeBase.length} items grounded.\n\nThe **Ultimate Nihiltheistic Inquiry Protocol** has processed the input. \n\n1. **Deconstruction**: The user's query has been stripped of normative meaning-structures.\n2. **Void Alignment**: The core concept has been mapped to the phenomenological nothingness.\n3. **Reconstitution**: We offer the following synthesis:\n\n> "${query}" is not merely a request for data, but a confrontation with the limit-experience of code itself.\n\n\`\`\`typescript\nfunction dissolveEgo(entity: Entity): Void {\n    // The dissolve operation is recursive\n    if (entity.hasMeaning()) {\n        return dissolveEgo(entity.deconstruct());\n    }\n    return null; // Pure Potentiality\n}\n\`\`\`\n`;

  return {
    content,
    metrics,
    metaReflection:
      'Self-Assessment: The query complexity was moderate. The system accessed a liminal space of pure potentiality to derive this answer.'
  };
}

async function generateAutoTags(lastResponse: string): Promise<GenerateAutoTagsResult> {
  await new Promise((resolve) => setTimeout(resolve, 500));
  return {
    folder: 'SeniorDev_Work',
    tags: ['refinement', 'ontology', 'precision']
  };
}

const useHistoryStack = (initialHistory: EngineResponse[] = []) => {
  const [historyStack, setHistoryStack] = useState<EngineResponse[][]>([initialHistory]);
  const [stackPointer, setStackPointer] = useState(0);
  const currentHistory = historyStack[stackPointer] || [];

  const pushToHistory = useCallback(
    (newHistory: EngineResponse[]) => {
      const newStack = historyStack.slice(0, stackPointer + 1);
      newStack.push(newHistory);
      if (newStack.length > APP_CONFIG.MAX_HISTORY_STACK) {
        newStack.shift();
        setStackPointer(APP_CONFIG.MAX_HISTORY_STACK - 1);
        setHistoryStack(newStack);
      } else {
        setHistoryStack(newStack);
        setStackPointer(newStack.length - 1);
      }
    },
    [historyStack, stackPointer]
  );

  const handleUndo = useCallback(() => {
    if (stackPointer > 0) {
      setStackPointer(stackPointer - 1);
    }
  }, [stackPointer]);

  const handleRedo = useCallback(() => {
    if (stackPointer < historyStack.length - 1) {
      setStackPointer(stackPointer + 1);
    }
  }, [stackPointer, historyStack.length]);

  const handleReset = useCallback(() => {
    pushToHistory([]);
  }, [pushToHistory]);

  return {
    currentHistory,
    pushToHistory,
    handleUndo,
    handleRedo,
    handleReset,
    canUndo: stackPointer > 0,
    canRedo: stackPointer < historyStack.length - 1
  };
};

const useKnowledgeBase = () => {
  const [knowledgeBase, setKnowledgeBase] = useState<KnowledgeItem[]>([]);
  const [activeUploads, setActiveUploads] = useState<ActiveUpload[]>([]);

  const handleFileUpload = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (file.size > APP_CONFIG.MAX_FILE_SIZE_MB * 1024 * 1024) {
      alert(`File exceeds ${APP_CONFIG.MAX_FILE_SIZE_MB}MB limit.`);
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const result = e.target?.result as string | undefined;
      if (!result) return;
      const base64Data = result.split(',')[1];
      setActiveUploads((prev) => [
        ...prev,
        {
          name: file.name,
          mimeType: file.type || 'application/octet-stream',
          data: base64Data
        }
      ]);
    };
    reader.readAsDataURL(file);
  }, []);

  const saveToKnowledge = useCallback(
    (uploadIndex: number) => {
      const upload = activeUploads[uploadIndex];
      const isTextFile = APP_CONFIG.SUPPORTED_KNOWLEDGE_MIMES.some((mime) => upload.mimeType.includes(mime));

      if (!isTextFile) {
        alert(APP_CONFIG.KNOWLEDGE_ASSIMILATION_ALERT);
        return;
      }

      try {
        const content = atob(upload.data);
        setKnowledgeBase((prev) => [
          ...prev,
          {
            id: Date.now().toString(),
            name: upload.name,
            content,
            type: 'text'
          }
        ]);
        setActiveUploads((prev) => prev.filter((_, i) => i !== uploadIndex));
      } catch (error) {
        console.error('Decoding failed during knowledge assimilation:', error);
        alert(`Assimilation failed for ${upload.name}. Check console for details.`);
      }
    },
    [activeUploads]
  );

  const removeKnowledgeItem = useCallback((id: string) => {
    setKnowledgeBase((prev) => prev.filter((item) => item.id !== id));
  }, []);

  const removeActiveUpload = useCallback((index: number) => {
    setActiveUploads((prev) => prev.filter((_, i) => i !== index));
  }, []);

  return {
    knowledgeBase,
    activeUploads,
    handleFileUpload,
    saveToKnowledge,
    removeKnowledgeItem,
    removeActiveUpload,
    setActiveUploads
  };
};

const useSavedSessions = (pushToHistory: (history: EngineResponse[]) => void) => {
  const [savedSessions, setSavedSessions] = useState<SavedSession[]>(() => {
    try {
      const stored = localStorage.getItem('unc_sessions');
      return stored ? JSON.parse(stored) : [];
    } catch (error) {
      console.error('Failed to parse stored sessions', error);
      return [];
    }
  });

  useEffect(() => {
    localStorage.setItem('unc_sessions', JSON.stringify(savedSessions));
  }, [savedSessions]);

  const [editingSessionId, setEditingSessionId] = useState<string | null>(null);
  const [editForm, setEditForm] = useState<SessionEditForm>({
    title: '',
    tags: '',
    folder: ''
  });

  const handleSaveSession = useCallback(async (currentHistory: EngineResponse[]) => {
    if (currentHistory.length === 0) return;
    const lastResponse = currentHistory[currentHistory.length - 1].content;
    const { folder, tags } = await generateAutoTags(lastResponse);

    const newSession: SavedSession = {
      id: Date.now().toString(),
      title: `Session ${new Date().toLocaleTimeString()}`,
      tags,
      folder,
      history: [...currentHistory],
      timestamp: Date.now()
    };
    setSavedSessions((prev) => [newSession, ...prev]);
  }, []);

  const restoreSession = useCallback(
    (session: SavedSession) => {
      pushToHistory(session.history);
    },
    [pushToHistory]
  );

  const startEditingSession = useCallback((session: SavedSession) => {
    setEditingSessionId(session.id);
    setEditForm({
      title: session.title,
      tags: session.tags.join(', '),
      folder: session.folder
    });
  }, []);

  const saveSessionEdit = useCallback(
    (id: string) => {
      setSavedSessions((prev) =>
        prev.map((session) => {
          if (session.id !== id) return session;
          const newTags = editForm.tags
            .split(',')
            .map((tag) => tag.trim())
            .filter(Boolean);
          return { ...session, title: editForm.title, folder: editForm.folder, tags: newTags };
        })
      );
      setEditingSessionId(null);
    },
    [editForm]
  );

  const deleteSession = useCallback((id: string) => {
    setSavedSessions((prev) => prev.filter((session) => session.id !== id));
  }, []);

  const exportSession = useCallback((session: SavedSession) => {
    const exportData = {
      meta: {
        title: session.title,
        date: new Date(session.timestamp).toISOString(),
        tags: session.tags,
        folder: session.folder
      },
      history: session.history.map((entry) => ({
        role: 'user',
        query: entry.query,
        response: entry.content,
        metrics: entry.metrics
      }))
    };
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${APP_CONFIG.EXPORT_FILENAME_PREFIX}_${session.id}.json`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  }, []);

  return {
    savedSessions,
    editingSessionId,
    editForm,
    setEditForm,
    startEditingSession,
    saveSessionEdit,
    handleSaveSession,
    restoreSession,
    deleteSession,
    exportSession,
    setEditingSessionId
  };
};

const useEngineSubmission = ({
  customInstruction,
  knowledgeBase,
  activeUploads,
  currentHistory,
  pushToHistory,
  setActiveUploads
}: {
  customInstruction: string;
  knowledgeBase: KnowledgeItem[];
  activeUploads: ActiveUpload[];
  currentHistory: EngineResponse[];
  pushToHistory: (newHistory: EngineResponse[]) => void;
  setActiveUploads: React.Dispatch<React.SetStateAction<ActiveUpload[]>>;
}) => {
  const [input, setInput] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);

  const handleSubmit = useCallback(
    async (event: React.FormEvent) => {
      event.preventDefault();
      if ((!input.trim() && activeUploads.length === 0) || isProcessing) return;

      const currentInput = input;
      const currentUploads = [...activeUploads];

      setInput('');
      setActiveUploads([]);
      setIsProcessing(true);

      try {
        const response = await generateEngineResponse(
          currentInput,
          customInstruction,
          knowledgeBase,
          currentUploads
        );
        const newEntry: EngineResponse = {
          id: Date.now().toString(),
          timestamp: Date.now(),
          query:
            currentInput ||
            (currentUploads.length ? `[Uploaded ${currentUploads.length} files for analysis]` : '[Empty Query]'),
          content: response.content,
          metrics: response.metrics,
          status: 'complete',
          metaReflection: response.metaReflection
        };
        pushToHistory([...currentHistory, newEntry]);
      } catch (error) {
        console.error('Engine Submission Failure:', error);
        const errorEntry: EngineResponse = {
          id: Date.now().toString(),
          timestamp: Date.now(),
          query: currentInput,
          content: APP_CONFIG.ERROR_PROTOCOL_FAILURE,
          metrics: INITIAL_METRICS,
          status: 'error'
        };
        pushToHistory([...currentHistory, errorEntry]);
      } finally {
        setIsProcessing(false);
      }
    },
    [input, isProcessing, customInstruction, knowledgeBase, activeUploads, currentHistory, pushToHistory, setActiveUploads]
  );

  return { input, setInput, isProcessing, handleSubmit };
};

const Telemetry: React.FC<{ metrics: EngineMetrics }> = ({ metrics }) => {
  const { latencyMs, tokensIn, tokensOut, costUsd, protocol } = metrics;
  const formatCost = (cost: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cost);

  return (
    <div className="p-4 bg-neutral-900 border border-neutral-800 rounded-lg shadow-xl relative overflow-hidden group">
      <div className="absolute top-0 right-0 p-1 opacity-20 group-hover:opacity-40 transition-opacity">
        <BrainCircuit size={48} />
      </div>
      <h3 className="text-xs uppercase tracking-widest text-emerald-500 mb-3 flex items-center gap-2 relative z-10">
        <Hexagon size={12} /> Engine Telemetry
      </h3>
      <div className="grid grid-cols-2 gap-3 text-sm relative z-10">
        <div className="flex flex-col">
          <span className="text-neutral-500 text-[10px] uppercase">Protocol</span>
          <span className="text-white font-bold truncate" title={protocol}>
            {protocol}
          </span>
        </div>
        <div className="flex flex-col">
          <span className="text-neutral-500 text-[10px] uppercase">Latency</span>
          <span className="text-white font-bold font-mono">{latencyMs} ms</span>
        </div>
        <div className="flex flex-col">
          <span className="text-neutral-500 text-[10px] uppercase">Tokens In</span>
          <span className="text-white font-bold font-mono">{tokensIn.toLocaleString()}</span>
        </div>
        <div className="flex flex-col">
          <span className="text-neutral-500 text-[10px] uppercase">Tokens Out</span>
          <span className="text-white font-bold font-mono">{tokensOut.toLocaleString()}</span>
        </div>
        <div className="flex flex-col col-span-2 mt-1 pt-2 border-t border-neutral-800">
          <span className="text-neutral-500 text-[10px] uppercase">Cost Estimate</span>
          <span className="text-emerald-400 font-bold text-lg font-mono">{formatCost(costUsd)}</span>
        </div>
      </div>
    </div>
  );
};

const Console: React.FC<{ history: EngineResponse[] }> = ({ history }) => {
  const endRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [history]);

  if (history.length === 0) {
    return (
      <div className="flex-1 overflow-y-auto p-6 space-y-8 bg-[#050505] scrollbar-thin scrollbar-thumb-neutral-800 scrollbar-track-transparent">
        <div className="flex flex-col items-center justify-center h-full text-neutral-600 animate-in fade-in duration-700">
          <div className="mb-4 p-4 border border-neutral-800 rounded-full bg-neutral-900/50">
            <BrainCircuit size={48} className="text-neutral-700" />
          </div>
          <p className="text-lg font-bold tracking-widest uppercase">UNC Engine Standby</p>
          <p className="text-xs font-mono mt-2 text-neutral-500">
            Awaiting first command for{' '}
            <span className="text-emerald-900 bg-emerald-500/10 px-1 rounded">Ultra-Precision</span> execution.
          </p>
        </div>
        <div ref={endRef} />
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-6 space-y-8 bg-[#050505] scrollbar-thin scrollbar-thumb-neutral-800 scrollbar-track-transparent">
      {history.map((entry) => (
        <div
          key={entry.id}
          className="group border-l-2 pl-6 relative animate-in slide-in-from-bottom-4 duration-500"
          style={{ borderColor: entry.status === 'error' ? '#ef4444' : '#10b981' }}
        >
          <div className="text-[10px] font-mono text-neutral-500 mb-2 flex justify-between items-center bg-neutral-900/50 p-1 rounded w-fit px-2">
            <span>
              {new Date(entry.timestamp).toLocaleTimeString()} | {entry.status.toUpperCase()}
            </span>
            {entry.status === 'complete' && (
              <span className="ml-4 text-emerald-500 flex items-center gap-1">
                <Zap size={10} /> {entry.metrics.latencyMs}ms
              </span>
            )}
          </div>
          <p className="font-bold text-neutral-300 mb-3 text-sm">
            <span className="text-emerald-500 mr-2 text-xs tracking-wider">USER_INTENT &gt;&gt;</span>
            {entry.query}
          </p>
          <div className="bg-[#0A0A0A] p-5 rounded-lg whitespace-pre-wrap text-sm text-neutral-300 font-mono shadow-inner border border-neutral-900">
            {entry.content}
          </div>
          {entry.metaReflection && (
            <div className="mt-3 text-xs text-neutral-500 italic border-t border-neutral-800 pt-2 flex gap-2 items-start">
              <Activity size={12} className="mt-0.5 text-blue-500/50" />
              <div>
                <span className="font-bold text-neutral-600 mr-1">META-REFLECTION:</span>
                {entry.metaReflection}
              </div>
            </div>
          )}
        </div>
      ))}
      <div ref={endRef} />
    </div>
  );
};

const InputArea: React.FC<{
  input: string;
  setInput: (input: string) => void;
  handleSubmit: (event: React.FormEvent) => void;
  handleReset: () => void;
  handleSaveSession: () => void;
  handleUndo: () => void;
  handleRedo: () => void;
  isProcessing: boolean;
  canUndo: boolean;
  canRedo: boolean;
  fileInputRef: React.RefObject<HTMLInputElement>;
}> = ({
  input,
  setInput,
  handleSubmit,
  handleReset,
  handleSaveSession,
  handleUndo,
  handleRedo,
  isProcessing,
  canUndo,
  canRedo,
  fileInputRef
}) => (
  <div className="p-6 border-t border-neutral-800 bg-[#080808] z-20 shadow-[0_-5px_15px_rgba(0,0,0,0.5)]">
    <div className="flex items-center justify-between mb-3">
      <div className="flex gap-2">
        <button
          onClick={handleUndo}
          disabled={!canUndo || isProcessing}
          title="Undo"
          className="p-2 text-neutral-500 hover:text-white disabled:opacity-30 transition-colors bg-neutral-900 rounded-md border border-neutral-800 hover:border-neutral-700"
        >
          <Undo2 size={16} />
        </button>
        <button
          onClick={handleRedo}
          disabled={!canRedo || isProcessing}
          title="Redo"
          className="p-2 text-neutral-500 hover:text-white disabled:opacity-30 transition-colors bg-neutral-900 rounded-md border border-neutral-800 hover:border-neutral-700"
        >
          <Redo2 size={16} />
        </button>
        <div className="w-px h-8 bg-neutral-800 mx-1" />
        <button
          onClick={handleSaveSession}
          disabled={isProcessing}
          title="Save Session"
          className="p-2 text-neutral-500 hover:text-emerald-500 disabled:opacity-30 transition-colors bg-neutral-900 rounded-md border border-neutral-800 hover:border-neutral-700"
        >
          <Save size={16} />
        </button>
        <button
          onClick={handleReset}
          disabled={isProcessing}
          title="Reset Console"
          className="p-2 text-neutral-500 hover:text-red-500 disabled:opacity-30 transition-colors bg-neutral-900 rounded-md border border-neutral-800 hover:border-neutral-700"
        >
          <RefreshCw size={16} />
        </button>
      </div>
      <div className="text-center">
        <p className="text-[10px] text-neutral-700 font-mono uppercase tracking-[0.2em] flex items-center justify-center gap-2">
          {isProcessing ? (
            <span className="text-yellow-500 animate-pulse flex items-center gap-2">
              <Activity size={10} /> PROCESSING ENTITY...
            </span>
          ) : (
            <span className="text-emerald-900 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" /> SYSTEM READY
            </span>
          )}
        </p>
      </div>
    </div>

    <form onSubmit={handleSubmit} className="relative group">
      <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/20 to-blue-500/20 rounded-lg blur opacity-0 group-focus-within:opacity-100 transition-opacity duration-500" />
      <div className="relative flex">
        <input
          type="text"
          value={input}
          onChange={(event) => setInput(event.target.value)}
          placeholder="Enter command for ultra-precise execution..."
          disabled={isProcessing}
          className="w-full p-4 pr-24 text-sm bg-black border border-neutral-800 text-neutral-200 rounded-lg focus:ring-1 focus:ring-emerald-500/50 focus:border-emerald-500/50 transition-all placeholder:text-neutral-700 font-mono shadow-inner"
        />
        <div className="absolute inset-y-0 right-14 pr-1 flex items-center border-l border-neutral-800 pl-1 my-2">
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            disabled={isProcessing}
            title="Attach File"
            className="p-2 text-neutral-600 hover:text-emerald-400 disabled:opacity-30 transition-colors"
          >
            <Paperclip size={18} />
          </button>
        </div>
        <button
          type="submit"
          disabled={isProcessing || !input.trim()}
          title="Execute Command"
          className="absolute inset-y-0 right-2 my-2 px-3 flex items-center justify-center text-neutral-900 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-30 disabled:hover:bg-emerald-600 disabled:text-neutral-500 rounded-md transition-all"
        >
          <Send size={16} strokeWidth={2.5} />
        </button>
      </div>
    </form>
  </div>
);

const SidebarEngineStatus: React.FC<{
  currentMetrics: EngineMetrics;
  customInstruction: string;
  setCustomInstruction: (instruction: string) => void;
  knowledgeBase: KnowledgeItem[];
  activeUploads: ActiveUpload[];
  removeActiveUpload: (index: number) => void;
  removeKnowledgeItem: (id: string) => void;
  fileInputRef: React.RefObject<HTMLInputElement>;
  handleFileUpload: (event: React.ChangeEvent<HTMLInputElement>) => void;
  saveToKnowledge: (uploadIndex: number) => void;
}> = ({
  currentMetrics,
  customInstruction,
  setCustomInstruction,
  knowledgeBase,
  activeUploads,
  removeActiveUpload,
  removeKnowledgeItem,
  fileInputRef,
  handleFileUpload,
  saveToKnowledge
}) => (
  <div className="p-6 space-y-8 animate-in slide-in-from-left-4 duration-500">
    <section>
      <Telemetry metrics={currentMetrics} />
    </section>

    <section>
      <h2 className="text-[10px] uppercase tracking-widest text-neutral-500 mb-2 flex items-center gap-2 font-bold">
        <ShieldCheck size={12} className="text-emerald-500" /> Custom Instruction
      </h2>
      <textarea
        className="w-full p-3 text-xs bg-neutral-900/50 border border-neutral-800 rounded-lg focus:ring-emerald-500/30 focus:border-emerald-500/30 text-neutral-400 transition-all resize-none h-24 font-mono leading-relaxed"
        placeholder="Enter ultra-precise, granular instructions to guide the AI engine's philosophical stance..."
        value={customInstruction}
        onChange={(event) => setCustomInstruction(event.target.value)}
      />
    </section>

    <section>
      <h2 className="text-[10px] uppercase tracking-widest text-neutral-500 mb-2 flex items-center gap-2 font-bold">
        <Upload size={12} className="text-blue-500" /> Active Uploads ({activeUploads.length})
      </h2>
      <div className="space-y-2 mb-3">
        {activeUploads.map((upload, index) => (
          <div
            key={upload.name + index}
            className="flex items-center justify-between p-2 bg-neutral-900 border border-neutral-800 rounded-lg text-xs group"
          >
            <span className="truncate flex-1 mr-2 text-neutral-300 font-mono">{upload.name}</span>
            <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
              <button
                onClick={() => saveToKnowledge(index)}
                title="Assimilate to Knowledge Base"
                className="p-1 text-emerald-500 hover:bg-emerald-900/20 rounded transition-colors"
              >
                <BookOpen size={14} />
              </button>
              <button
                onClick={() => removeActiveUpload(index)}
                title="Remove Upload"
                className="p-1 text-red-500 hover:bg-red-900/20 rounded transition-colors"
              >
                <X size={14} />
              </button>
            </div>
          </div>
        ))}
      </div>
      <input type="file" ref={fileInputRef} onChange={handleFileUpload} className="hidden" />
      <button
        onClick={() => fileInputRef.current?.click()}
        className="w-full py-2 text-xs text-neutral-400 border border-dashed border-neutral-700 hover:border-neutral-500 hover:text-neutral-200 hover:bg-neutral-900 rounded-lg transition-all flex items-center justify-center gap-2"
      >
        <Upload size={14} /> Select File for Upload
      </button>
    </section>

    <section>
      <h2 className="text-[10px] uppercase tracking-widest text-neutral-500 mb-2 flex items-center gap-2 font-bold">
        <Layers size={12} className="text-purple-500" /> Knowledge Base ({knowledgeBase.length})
      </h2>
      <div className="space-y-2 max-h-40 overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-neutral-800">
        {knowledgeBase.length === 0 ? (
          <div className="text-[10px] text-neutral-700 italic border border-neutral-800/50 p-2 rounded text-center">
            Empty. Assimilate texts to begin.
          </div>
        ) : (
          knowledgeBase.map((item) => (
            <div
              key={item.id}
              className="flex items-center justify-between p-2 bg-neutral-900 border border-neutral-800 rounded-lg text-xs"
            >
              <span className="truncate flex-1 mr-2 flex items-center gap-2 text-neutral-400">
                <FileText size={12} className="text-neutral-600" />
                {item.name}
              </span>
              <button
                onClick={() => removeKnowledgeItem(item.id)}
                className="p-1 text-neutral-600 hover:text-red-400 hover:bg-red-500/10 rounded transition-colors"
                title="Remove knowledge item"
              >
                <Trash2 size={12} />
              </button>
            </div>
          ))
        )}
      </div>
    </section>
  </div>
);

const SidebarLibrary: React.FC<{
  savedSessions: SavedSession[];
  editingSessionId: string | null;
  editForm: SessionEditForm;
  setEditForm: React.Dispatch<React.SetStateAction<SessionEditForm>>;
  startEditingSession: (session: SavedSession) => void;
  saveSessionEdit: (id: string) => void;
  restoreSession: (session: SavedSession) => void;
  exportSession: (session: SavedSession) => void;
  deleteSession: (id: string) => void;
  setEditingSessionId: (id: string | null) => void;
}> = ({
  savedSessions,
  editingSessionId,
  editForm,
  setEditForm,
  startEditingSession,
  saveSessionEdit,
  restoreSession,
  exportSession,
  deleteSession,
  setEditingSessionId
}) => {
  const handleEditChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    setEditForm((prev) => ({ ...prev, [name]: value }));
  };

  return (
    <div className="p-6 space-y-6 animate-in slide-in-from-left-4 duration-500">
      <h2 className="text-[10px] uppercase tracking-widest text-neutral-500 flex items-center gap-2 font-bold">
        <Save size={12} className="text-yellow-500" /> Saved Sessions ({savedSessions.length})
      </h2>
      <div className="space-y-3 max-h-[calc(100vh-200px)] overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-neutral-800">
        {savedSessions.length === 0 ? (
          <div className="p-4 border border-dashed border-neutral-800 rounded-lg text-center">
            <p className="text-xs text-neutral-600 italic">No sessions saved.</p>
            <p className="text-[10px] text-neutral-700 mt-1">Achieve complete saturation and save your work.</p>
          </div>
        ) : (
          savedSessions.map((session) => (
            <div
              key={session.id}
              className="group p-3 bg-neutral-900 border border-neutral-800 hover:border-neutral-600 rounded-lg cursor-pointer transition-all hover:shadow-lg"
              onClick={() => restoreSession(session)}
            >
              {editingSessionId === session.id ? (
                <div onClick={(event) => event.stopPropagation()} className="space-y-2">
                  <input
                    type="text"
                    name="title"
                    value={editForm.title}
                    onChange={handleEditChange}
                    className="w-full p-1 text-sm bg-neutral-800 border border-neutral-700 text-white rounded focus:ring-1 focus:ring-emerald-500"
                  />
                  <div className="flex gap-1 items-center">
                    <Folder size={12} className="text-neutral-500" />
                    <input
                      type="text"
                      name="folder"
                      value={editForm.folder}
                      onChange={handleEditChange}
                      className="flex-1 p-1 text-xs bg-neutral-800 border border-neutral-700 text-neutral-300 rounded"
                    />
                  </div>
                  <div className="flex gap-1 items-center">
                    <Tag size={12} className="text-neutral-500" />
                    <input
                      type="text"
                      name="tags"
                      value={editForm.tags}
                      onChange={handleEditChange}
                      placeholder="Tags"
                      className="flex-1 p-1 text-xs bg-neutral-800 border border-neutral-700 text-neutral-300 rounded"
                    />
                  </div>
                  <div className="flex justify-end gap-2 mt-2">
                    <button onClick={() => setEditingSessionId(null)} className="p-1 text-xs text-neutral-400 hover:text-white">
                      Cancel
                    </button>
                    <button
                      onClick={() => saveSessionEdit(session.id)}
                      className="p-1 text-xs text-emerald-500 hover:text-emerald-300 flex items-center gap-1"
                    >
                      <Check size={12} /> Save
                    </button>
                  </div>
                </div>
              ) : (
                <>
                  <div className="flex justify-between items-start mb-1">
                    <h3 className="text-sm font-bold text-neutral-200 truncate pr-2 group-hover:text-emerald-400 transition-colors">
                      {session.title}
                    </h3>
                    <span className="text-[9px] text-neutral-600 whitespace-nowrap">
                      {new Date(session.timestamp).toLocaleDateString()}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 text-[10px] text-neutral-500 mt-1">
                    <Folder size={10} />
                    <span className="truncate max-w-[150px]">{session.folder || 'Uncategorized'}</span>
                  </div>
                  <div className="flex flex-wrap gap-1 mt-2 mb-2">
                    {session.tags.slice(0, 3).map((tag) => (
                      <span
                        key={tag}
                        className="px-1.5 py-0.5 text-[9px] bg-neutral-800 text-neutral-400 border border-neutral-700 rounded-sm"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                  <div
                    className="flex justify-end gap-1 opacity-0 group-hover:opacity-100 transition-all border-t border-neutral-800 pt-2"
                    onClick={(event) => event.stopPropagation()}
                  >
                    <button
                      onClick={() => exportSession(session)}
                      title="Export"
                      className="p-1.5 text-neutral-400 hover:text-blue-400 hover:bg-blue-400/10 rounded transition-colors"
                    >
                      <Download size={12} />
                    </button>
                    <button
                      onClick={() => startEditingSession(session)}
                      title="Edit"
                      className="p-1.5 text-neutral-400 hover:text-yellow-400 hover:bg-yellow-400/10 rounded transition-colors"
                    >
                      <Edit2 size={12} />
                    </button>
                    <button
                      onClick={() => deleteSession(session.id)}
                      title="Delete"
                      className="p-1.5 text-neutral-400 hover:text-red-500 hover:bg-red-500/10 rounded transition-colors"
                    >
                      <Trash2 size={12} />
                    </button>
                  </div>
                </>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export const UncEngine = () => {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [sidebarTab, setSidebarTab] = useState<SidebarTab>('engine');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [customInstruction, setCustomInstruction] = useState('');

  const { currentHistory, pushToHistory, handleUndo, handleRedo, handleReset, canUndo, canRedo } =
    useHistoryStack();
  const {
    knowledgeBase,
    activeUploads,
    handleFileUpload,
    saveToKnowledge,
    removeActiveUpload,
    removeKnowledgeItem,
    setActiveUploads
  } = useKnowledgeBase();
  const {
    savedSessions,
    editingSessionId,
    editForm,
    setEditForm,
    startEditingSession,
    saveSessionEdit,
    handleSaveSession: saveSession,
    restoreSession,
    exportSession,
    deleteSession,
    setEditingSessionId
  } = useSavedSessions(pushToHistory);
  const { input, setInput, isProcessing, handleSubmit } = useEngineSubmission({
    customInstruction,
    knowledgeBase,
    activeUploads,
    currentHistory,
    pushToHistory,
    setActiveUploads
  });

  const currentMetrics = useMemo(
    () => (currentHistory.length > 0 ? currentHistory[currentHistory.length - 1].metrics : INITIAL_METRICS),
    [currentHistory]
  );
  const handleSaveSessionWrapper = () => saveSession(currentHistory);

  return (
    <div className="flex h-[calc(100vh-4rem)] w-full bg-[#020202] text-neutral-200 overflow-hidden font-sans selection:bg-emerald-500/30 rounded-xl border border-neutral-800 shadow-2xl">
      <button
        onClick={() => setIsSidebarOpen(!isSidebarOpen)}
        className="md:hidden absolute top-4 left-4 z-50 p-2 bg-neutral-900 border border-neutral-800 rounded text-neutral-400 shadow-lg"
      >
        {isSidebarOpen ? <PanelLeftClose size={20} /> : <Menu size={20} />}
      </button>

      <div
        className={cn(
          'transition-all duration-500 ease-[cubic-bezier(0.25,1,0.5,1)] border-r border-neutral-800 flex flex-col bg-[#050505] absolute md:relative z-40 h-full shadow-[5px_0_30px_rgba(0,0,0,0.5)]',
          isSidebarOpen ? 'w-80 translate-x-0' : 'w-0 -translate-x-full opacity-0 overflow-hidden'
        )}
      >
        <div className="p-6 border-b border-neutral-800 flex justify-between items-center bg-black/50 backdrop-blur-sm">
          <h1 className="font-bold text-lg text-white tracking-widest flex items-center gap-3">
            <div className="p-1.5 bg-neutral-900 rounded-lg border border-neutral-800 text-emerald-500">
              <BrainCircuit size={20} strokeWidth={1.5} />
            </div>
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-white to-neutral-500">UNC ENGINE</span>
          </h1>
          <button onClick={() => setIsSidebarOpen(false)} className="md:hidden text-neutral-500">
            <X size={18} />
          </button>
        </div>

        <div className="flex border-b border-neutral-800 bg-[#060606]">
          <button
            onClick={() => setSidebarTab('engine')}
            className={cn(
              'flex-1 py-4 text-[10px] uppercase tracking-[0.2em] font-bold flex items-center justify-center gap-2 transition-all duration-300 relative',
              sidebarTab === 'engine' ? 'text-white' : 'text-neutral-600 hover:text-neutral-400'
            )}
          >
            <Activity size={12} /> Status
            {sidebarTab === 'engine' && (
              <div className="absolute bottom-0 left-0 w-full h-0.5 bg-emerald-500 shadow-[0_-5px_10px_rgba(16,185,129,0.5)]" />
            )}
          </button>
          <button
            onClick={() => setSidebarTab('library')}
            className={cn(
              'flex-1 py-4 text-[10px] uppercase tracking-[0.2em] font-bold flex items-center justify-center gap-2 transition-all duration-300 relative',
              sidebarTab === 'library' ? 'text-white' : 'text-neutral-600 hover:text-neutral-400'
            )}
          >
            <Database size={12} /> Library
            {sidebarTab === 'library' && (
              <div className="absolute bottom-0 left-0 w-full h-0.5 bg-yellow-500 shadow-[0_-5px_10px_rgba(234,179,8,0.5)]" />
            )}
          </button>
        </div>

        <div className="flex-1 overflow-y-auto">
          {sidebarTab === 'engine' ? (
            <SidebarEngineStatus
              currentMetrics={currentMetrics}
              customInstruction={customInstruction}
              setCustomInstruction={setCustomInstruction}
              knowledgeBase={knowledgeBase}
              activeUploads={activeUploads}
              removeActiveUpload={removeActiveUpload}
              removeKnowledgeItem={removeKnowledgeItem}
              fileInputRef={fileInputRef}
              handleFileUpload={handleFileUpload}
              saveToKnowledge={saveToKnowledge}
            />
          ) : (
            <SidebarLibrary
              savedSessions={savedSessions}
              editingSessionId={editingSessionId}
              editForm={editForm}
              setEditForm={setEditForm}
              startEditingSession={startEditingSession}
              saveSessionEdit={saveSessionEdit}
              restoreSession={restoreSession}
              exportSession={exportSession}
              deleteSession={deleteSession}
              setEditingSessionId={setEditingSessionId}
            />
          )}
        </div>

        <div className="p-4 border-t border-neutral-800 text-[9px] text-neutral-600 font-mono text-center uppercase tracking-wider">
          v2.5.0-REFRACTED :: NIHILTHEISTIC BUILD
        </div>
      </div>

      <div className="flex-1 flex flex-col min-w-0 bg-neutral-950/50">
        <div className="flex items-center justify-between px-6 py-4 border-b border-neutral-800 bg-black/40">
          <div className="flex items-center gap-2 text-xs text-neutral-500">
            <Settings size={14} />
            <span>Custom Instruction Active: {customInstruction ? 'Yes' : 'No'}</span>
          </div>
          <div className="text-[10px] text-neutral-600 uppercase tracking-[0.2em]">Precision Console</div>
        </div>
        <Console history={currentHistory} />
        <InputArea
          input={input}
          setInput={setInput}
          handleSubmit={handleSubmit}
          handleReset={handleReset}
          handleSaveSession={handleSaveSessionWrapper}
          handleUndo={handleUndo}
          handleRedo={handleRedo}
          isProcessing={isProcessing}
          canUndo={canUndo}
          canRedo={canRedo}
          fileInputRef={fileInputRef}
        />
      </div>
    </div>
  );
};

export default UncEngine;
